content = open('d:/web_ban_da_muoi/frontend/src/app/admin/products/page.tsx', 'r', encoding='utf-8').read()

replacements = [
    ('Tim kiem san pham...', 'Tìm kiếm sản phẩm...'),
    ('Tao san pham', 'Tạo sản phẩm'),
    ('Danh sach san pham', 'Danh sách sản phẩm'),
    ('Tong cong', 'Tổng cộng'),
    ('Tim theo ten hoac SKU', 'Tìm theo tên hoặc SKU'),
    ('Tat ca danh muc', 'Tất cả danh mục'),
    ('Tat ca trang thai', 'Tất cả trạng thái'),
    ('>Dang ban<', '>Đang bán<'),
    ('>Da an<', '>Đã ẩn<'),
    ('">San pham</th>', '">Sản phẩm</th>'),
    ('">Danh muc</th>', '">Danh mục</th>'),
    ('">Gia ban</th>', '">Giá bán</th>'),
    ('">Ton kho</th>', '">Tồn kho</th>'),
    ('">Trang thai</th>', '">Trạng thái</th>'),
    ('">Thao tac</th>', '">Thao tác</th>'),
    ('Dang tai du lieu...', 'Đang tải dữ liệu...'),
    ('Khong tim thay san pham phu hop.', 'Không tìm thấy sản phẩm phù hợp.'),
    ('{product.stock} cai', '{product.stock} cái'),
    ('Hien thi {', 'Hiển thị {'),
    ('"Chinh sua San pham"', '"Chỉnh sửa Sản phẩm"'),
    ('"Them San pham Moi"', '"Thêm Sản phẩm Mới"'),
    ('Quan ly danh muc den da muoi Himalaya', 'Quản lý danh mục đèn đá muối Himalaya'),
    ('>Ten san pham', '>Tên sản phẩm'),
    ('Vi du: Den da muoi hinh cau tu nhien', 'Ví dụ: Đèn đá muối hình cầu tự nhiên'),
    ('>Mo ta chi tiet', '>Mô tả chi tiết'),
    ('Nhap mo ta chi tiet ve san pham, nguon goc va huong dan su dung...', 'Nhập mô tả chi tiết về sản phẩm, nguồn gốc và hướng dẫn sử dụng...'),
    ('>Gia ban (VND)', '>Giá bán (VND)'),
    ('>Gia goc / KM (VND)', '>Giá gốc / KM (VND)'),
    ('>So luong ton kho', '>Số lượng tồn kho'),
    ('>Cong dung', '>Công dụng'),
    ('>San pham noi bat', '>Sản phẩm nổi bật'),
    ('Hien thi noi bat tren trang chu', 'Hiển thị nổi bật trên trang chủ'),
    ('>Hinh anh san pham', '>Hình ảnh sản phẩm'),
    ('Tai anh len hoac keo tha', 'Tải ảnh lên hoặc kéo thả'),
    ('PNG, JPG toi da 5MB', 'PNG, JPG tối đa 5MB'),
    ('>Mo hinh 3D (GLB/GLTF)', '>Mô hình 3D (GLB/GLTF)'),
    ('Tai len mo hinh 3D hoac keo tha', 'Tải lên mô hình 3D hoặc kéo thả'),
    ('Ho tro dinh dang .glb, .gltf', 'Hỗ trợ định dạng .glb, .gltf'),
    ('>Xoa file 3D<', '>Xóa file 3D<'),
    ('"Chon danh muc"', '"Chọn danh mục"'),
    ('>Danh muc <span', '>Danh mục <span'),
    ('>Trang thai<', '>Trạng thái<'),
    ('Hien thi tren website', 'Hiển thị trên website'),
    ('"Huy"', '"Hủy"'),
    ('>Xac nhan xoa', '>Xác nhận xóa'),
    ('Hanh dong nay khong the hoan tac', 'Hành động này không thể hoàn tác'),
    ('Ban co chac chan muon xoa san pham', 'Bạn có chắc chắn muốn xóa sản phẩm'),
    ('" khong?', '" không?'),
    ('title="Chinh sua"', 'title="Chỉnh sửa"'),
    ('title="Xoa"', 'title="Xóa"'),
    ('>Xoa anh chinh<', '>Xóa ảnh chính<'),
    ('"Xoa san pham"', '"Xóa sản phẩm"'),
    ('"Dang xoa..."', '"Đang xóa..."'),
    ('"Dang luu..."', '"Đang lưu..."'),
    ('"Luu san pham"', '"Lưu sản phẩm"'),
    ('>SKU\n', '>SKU\n'),
    ('ID: {editProduct.id}', 'ID: {editProduct.id}'),
]

for old, new in replacements:
    content = content.replace(old, new)

with open('d:/web_ban_da_muoi/frontend/src/app/admin/products/page.tsx', 'w', encoding='utf-8') as f:
    f.write(content)
print('Done')
