"""add_cost_price_and_unit_cost

Revision ID: 18c19ca84eca
Revises: 9a89433413dd
Create Date: 2026-03-11 22:53:46.205209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '18c19ca84eca'
down_revision: Union[str, None] = '9a89433413dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = inspect(conn)
    
    # Kiểm tra cột cost_price trong products
    prod_columns = [col['name'] for col in inspector.get_columns('products')]
    if 'cost_price' not in prod_columns:
        op.add_column('products', sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=True))
        
    try:
        op.drop_index(op.f('ix_reviews_product_id'), table_name='reviews')
    except Exception:
        pass
        
    # Kiểm tra cột unit_cost trong stock_logs
    log_columns = [col['name'] for col in inspector.get_columns('stock_logs')]
    if 'unit_cost' not in log_columns:
        op.add_column('stock_logs', sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_logs', 'unit_cost')
    op.create_index(op.f('ix_reviews_product_id'), 'reviews', ['product_id'], unique=False)
    op.drop_column('products', 'cost_price')
    # ### end Alembic commands ###
