"""add_cost_price_and_unit_cost

Revision ID: 18c19ca84eca
Revises: 9a89433413dd
Create Date: 2026-03-11 22:53:46.205209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18c19ca84eca'
down_revision: Union[str, None] = '9a89433413dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.drop_index(op.f('ix_reviews_product_id'), table_name='reviews')
    op.add_column('stock_logs', sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_logs', 'unit_cost')
    op.create_index(op.f('ix_reviews_product_id'), 'reviews', ['product_id'], unique=False)
    op.drop_column('products', 'cost_price')
    # ### end Alembic commands ###
