"""drop unique product user review

Revision ID: 45cf770eb7de
Revises: 4be24e9ecb56
Create Date: 2026-03-11 21:27:39.883687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45cf770eb7de'
down_revision: Union[str, None] = '4be24e9ecb56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create an index on product_id so the foreign key is satisfied
    op.create_index('ix_reviews_product_id', 'reviews', ['product_id'])
    
    # Now drop the unique constraint
    op.drop_constraint('uq_review_product_user', 'reviews', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_review_product_user'), 'reviews', ['product_id', 'user_id'], unique=True)
    # ### end Alembic commands ###
