"""add_admin_reply_to_reviews

Revision ID: 4be24e9ecb56
Revises: bfe7e3aee7d4
Create Date: 2026-03-11 21:08:36.480229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4be24e9ecb56'
down_revision: Union[str, None] = 'bfe7e3aee7d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('admin_reply', sa.Text(), nullable=True))
    op.add_column('reviews', sa.Column('replied_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'replied_at')
    op.drop_column('reviews', 'admin_reply')
    # ### end Alembic commands ###
