"""add_min_stock_to_products

Revision ID: 9a89433413dd
Revises: 45cf770eb7de
Create Date: 2026-03-11 22:28:14.925258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '9a89433413dd'
down_revision: Union[str, None] = '45cf770eb7de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Kiểm tra xem cột min_stock đã tồn tại chưa để tránh lỗi
    conn = op.get_bind()
    inspector = inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('products')]
    
    if 'min_stock' not in columns:
        op.add_column('products', sa.Column('min_stock', sa.Integer(), nullable=False, server_default='10'))
        
    try:
        op.drop_index(op.f('ix_reviews_product_id'), table_name='reviews')
    except Exception:
        pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_reviews_product_id'), 'reviews', ['product_id'], unique=False)
    op.drop_column('products', 'min_stock')
    # ### end Alembic commands ###
